# Generated by Django 4.0.3 on 2022-04-16 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentproject',
            name='projectfile',
            field=models.FileField(default=0, upload_to=''),
        ),
    ]
