# Generated by Django 4.0.3 on 2022-04-16 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdashboard', '0002_studentproject_projectfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentproject',
            name='projectfile',
            field=models.FileField(default=0, upload_to='open-file'),
        ),
    ]
