# Generated by Django 4.0.3 on 2022-04-19 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdashboard', '0004_alter_studentproject_projectfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentproject',
            name='projectfile',
            field=models.FileField(default=0, upload_to='media/'),
        ),
    ]
